server.port: 7000

spring:
  application.name: gateway
  config:
    import: optional:file:.env[.properties]
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers Access-Control-Allow-Credentials RETAIN_FIRST 
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - ${CORS_ORIGIN1}
                  - ${CORS_ORIGIN2}
                  - ${CORS_ORIGIN3}
                  - ${CORS_ORIGIN4}
                allow-credentials: true
                allowedHeaders: 
                  - '*'
                allowedMethods:
                  - PUT
                  - GET
                  - POST
                  - PATCH
                  - DELETE
                  - OPTIONS
          routes:
            - id: oauth-service
              uri: ${ROUTE_OAUTH_URI}
              predicates:
                - Path=/oauth/**
              filters:
                - RewritePath=/oauth/?(?<segment>.*), /${segment}
                - ApiFilter
            - id: openapi
              uri: ${ROUTE_API_URI}
              predicates:
                - Path=/v3/api-docs/**
              filters:
                - RewritePath=/v3/api-docs/?(?<segment>.*), /${segment}/v3/api-docs
            - id: solo
              uri: ${ROUTE_SOLO_URI}
              predicates:
                - Path=/**
              filters:
                # - RewritePath=/solo/?(?<segment>.*), /${segment}
                - ApiFilter

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: gateway
  tracing:
    enabled: false
    sampling:
      probability: 1.0

springdoc:
  swagger-ui:
    # use-root-path: true
    path: /docs
    operationsSorter: method

logging.level.org.springframework: INFO
